version: '3.8'

services:
  mcp-server-qdrant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=test_collection
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      # Set QDRANT_API_KEY at runtime if needed
      # - QDRANT_API_KEY=your_secret_key
    depends_on:
      - qdrant
    networks:
      - mcp-network

  # Optional: Include Qdrant for testing
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  qdrant_storage: